"use client";

import { ColumnDef } from "@tanstack/react-table";

// This type is used to define the shape of our data.
// You can use a Zod schema here if you want.
export type Payment = {
  id: number;
  shipfyId: string;
  data: string;
  status: "pending" | "processing" | "success" | "failed";
  name: string;
  email: string;
  country: string;
  shipping: string;
  source: string;
  order_type: string;
};

export const columns: ColumnDef<Payment>[] = [
  {
    accessorKey: "id",
    header: () => <span className=" text-black font-bold">ID</span>,
  },
  {
    accessorKey: "shipfyId",
    header: () => <span className=" text-black font-bold">SHIPFYID</span>,
  },
  {
    accessorKey: "data",
    header: () => <span className=" text-black font-bold">DATE</span>,
  },
  {
    accessorKey: "status",
    header: () => <span className=" text-black font-bold">STATUS</span>,
  },
  {
    accessorKey: "name",
    header: () => <span className=" text-black font-bold">NAME</span>,
  },
  {
    accessorKey: "email",
    header: () => <span className=" text-black font-bold">EMAIL</span>,
  },
  {
    accessorKey: "country",
    header: () => <span className=" text-black font-bold">COUNTRY</span>,
  },
  {
    accessorKey: "shipping",
    header: () => <span className=" text-black font-bold">SHIPPING</span>,
  },
  {
    accessorKey: "source",
    header: () => <span className=" text-black font-bold">SOURCE</span>,
  },
  {
    accessorKey: "order_type",
    header: () => <span className=" text-black font-bold">ORDER TYPE</span>,
  },
];
export const payments: Payment[] = [
  {
    id: 1,
    shipfyId: "#5b64fb",
    data: "20-12-2023",
    status: "failed",
    name: "Roley Ventura",
    email: "rventura0@github.com",
    country: "Cuba",
    shipping: "0 Tennyson Trail",
    source: "WooCommerce",
    order_type: "phone",
  },
  {
    id: 2,
    shipfyId: "#f646d5",
    data: "25-02-2023",
    status: "success",
    name: "Celinda Pinckney",
    email: "cpinckney1@cocolog-nifty.com",
    country: "China",
    shipping: "69 Mallard Junction",
    source: "Shopify",
    order_type: "online",
  },
  {
    id: 3,
    shipfyId: "#333bab",
    data: "27-03-2023",
    status: "pending",
    name: "Isabelle Gregson",
    email: "igregson2@go.com",
    country: "Canada",
    shipping: "2858 Corben Plaza",
    source: "WooCommerce",
    order_type: "online",
  },
  {
    id: 4,
    shipfyId: "#b5a9c0",
    data: "05-06-2023",
    status: "processing",
    name: "Othello Marrett",
    email: "omarrett3@netlog.com",
    country: "Ecuador",
    shipping: "8 Crest Line Trail",
    source: "Magento",
    order_type: "online",
  },
  {
    id: 5,
    shipfyId: "#040203",
    data: "22-03-2023",
    status: "success",
    name: "Minor Blades",
    email: "mblades4@tamu.edu",
    country: "China",
    shipping: "27392 Katie Circle",
    source: "Magento",
    order_type: "phone",
  },
  {
    id: 6,
    shipfyId: "#f95c24",
    data: "13-10-2023",
    status: "success",
    name: "Candi Zahor",
    email: "czahor5@lulu.com",
    country: "Nigeria",
    shipping: "68970 South Place",
    source: "Shopware",
    order_type: "phone",
  },
  {
    id: 7,
    shipfyId: "#51d868",
    data: "11-09-2023",
    status: "processing",
    name: "Mikael Cordle",
    email: "mcordle6@cbsnews.com",
    country: "China",
    shipping: "8 Fairview Circle",
    source: "BigCommerce",
    order_type: "online",
  },
  {
    id: 8,
    shipfyId: "#4525a1",
    data: "01-09-2023",
    status: "processing",
    name: "Sidonnie Powlesland",
    email: "spowlesland7@163.com",
    country: "Russia",
    shipping: "0231 Continental Street",
    source: "WooCommerce",
    order_type: "mobile app",
  },
  {
    id: 9,
    shipfyId: "#ad28df",
    data: "22-07-2023",
    status: "pending",
    name: "Florella Bloan",
    email: "fbloan8@homestead.com",
    country: "China",
    shipping: "8 Tennyson Park",
    source: "Shopify",
    order_type: "in-store",
  },
  {
    id: 10,
    shipfyId: "#4bdd5a",
    data: "14-03-2023",
    status: "processing",
    name: "Debbie Bonham",
    email: "dbonham9@liveinternet.ru",
    country: "Indonesia",
    shipping: "341 Londonderry Pass",
    source: "Shopify",
    order_type: "online",
  },
  {
    id: 11,
    shipfyId: "#91011e",
    data: "28-06-2023",
    status: "processing",
    name: "Demetrius Baynes",
    email: "dbaynesa@elpais.com",
    country: "Sweden",
    shipping: "26 Heath Lane",
    source: "WooCommerce",
    order_type: "in-store",
  },
  {
    id: 12,
    shipfyId: "#14f26f",
    data: "18-01-2024",
    status: "pending",
    name: "Zorina Sisnett",
    email: "zsisnettb@cloudflare.com",
    country: "Haiti",
    shipping: "5 Brickson Park Parkway",
    source: "BigCommerce",
    order_type: "mobile app",
  },
  {
    id: 13,
    shipfyId: "#762b03",
    data: "23-01-2024",
    status: "failed",
    name: "Florrie Whitwell",
    email: "fwhitwellc@xing.com",
    country: "China",
    shipping: "36478 Maple Avenue",
    source: "Shopify",
    order_type: "phone",
  },
  {
    id: 14,
    shipfyId: "#2b4e25",
    data: "05-12-2023",
    status: "processing",
    name: "Georgina Balthasar",
    email: "gbalthasard@loc.gov",
    country: "Costa Rica",
    shipping: "7524 Cambridge Avenue",
    source: "Magento",
    order_type: "in-store",
  },
  {
    id: 15,
    shipfyId: "#9c7fa6",
    data: "19-08-2023",
    status: "failed",
    name: "Salomon Gentzsch",
    email: "sgentzsche@jimdo.com",
    country: "China",
    shipping: "6678 Steensland Alley",
    source: "Magento",
    order_type: "mobile app",
  },
  {
    id: 16,
    shipfyId: "#9991cf",
    data: "24-08-2023",
    status: "processing",
    name: "Jermaine Chazerand",
    email: "jchazerandf@prnewswire.com",
    country: "China",
    shipping: "74276 Mccormick Parkway",
    source: "WooCommerce",
    order_type: "phone",
  },
  {
    id: 17,
    shipfyId: "#cdde0c",
    data: "06-01-2024",
    status: "success",
    name: "Bev Pellitt",
    email: "bpellittg@a8.net",
    country: "Afghanistan",
    shipping: "89 Bluestem Circle",
    source: "Shopware",
    order_type: "in-store",
  },
  {
    id: 18,
    shipfyId: "#585d55",
    data: "09-10-2023",
    status: "pending",
    name: "Xylia Gary",
    email: "xgaryh@wix.com",
    country: "Finland",
    shipping: "86 Continental Parkway",
    source: "Magento",
    order_type: "phone",
  },
  {
    id: 19,
    shipfyId: "#13f59c",
    data: "03-12-2023",
    status: "processing",
    name: "Benjamen Lingwood",
    email: "blingwoodi@nytimes.com",
    country: "China",
    shipping: "28 Fisk Hill",
    source: "BigCommerce",
    order_type: "online",
  },
  {
    id: 20,
    shipfyId: "#78278b",
    data: "24-10-2023",
    status: "pending",
    name: "Rhys Franke",
    email: "rfrankej@gnu.org",
    country: "United States",
    shipping: "3 Ridge Oak Alley",
    source: "WooCommerce",
    order_type: "in-store",
  },
  {
    id: 21,
    shipfyId: "#35054e",
    data: "11-11-2023",
    status: "pending",
    name: "Flore McVrone",
    email: "fmcvronek@twitter.com",
    country: "Mexico",
    shipping: "08 Mitchell Plaza",
    source: "Shopware",
    order_type: "in-store",
  },
  {
    id: 22,
    shipfyId: "#6d13fb",
    data: "08-11-2023",
    status: "failed",
    name: "Wiatt Crewes",
    email: "wcrewesl@biblegateway.com",
    country: "Brazil",
    shipping: "96367 Marquette Street",
    source: "WooCommerce",
    order_type: "mobile app",
  },
  {
    id: 23,
    shipfyId: "#83698e",
    data: "13-07-2023",
    status: "success",
    name: "Zacharie Smiths",
    email: "zsmithsm@ameblo.jp",
    country: "Russia",
    shipping: "647 Tennessee Hill",
    source: "WooCommerce",
    order_type: "phone",
  },
  {
    id: 24,
    shipfyId: "#9e4934",
    data: "28-03-2023",
    status: "processing",
    name: "Howey MacDuffie",
    email: "hmacduffien@comsenz.com",
    country: "Canada",
    shipping: "831 Moulton Street",
    source: "WooCommerce",
    order_type: "in-store",
  },
  {
    id: 25,
    shipfyId: "#c9e4ae",
    data: "04-01-2024",
    status: "processing",
    name: "Imogen Brayshay",
    email: "ibrayshayo@123-reg.co.uk",
    country: "Portugal",
    shipping: "466 Hanson Lane",
    source: "BigCommerce",
    order_type: "phone",
  },
  {
    id: 26,
    shipfyId: "#e0b923",
    data: "14-02-2024",
    status: "pending",
    name: "Ward Colloff",
    email: "wcolloffp@china.com.cn",
    country: "Australia",
    shipping: "7525 Paget Crossing",
    source: "Shopify",
    order_type: "in-store",
  },
  {
    id: 27,
    shipfyId: "#a48c09",
    data: "25-08-2023",
    status: "success",
    name: "Bevvy Beney",
    email: "bbeneyq@scribd.com",
    country: "Portugal",
    shipping: "7 Schiller Lane",
    source: "BigCommerce",
    order_type: "in-store",
  },
  {
    id: 28,
    shipfyId: "#27eb16",
    data: "04-05-2023",
    status: "pending",
    name: "Darrel Hardware",
    email: "dhardwarer@mozilla.com",
    country: "China",
    shipping: "1 Mifflin Court",
    source: "BigCommerce",
    order_type: "in-store",
  },
  {
    id: 29,
    shipfyId: "#f00352",
    data: "05-10-2023",
    status: "pending",
    name: "Fletcher McCheyne",
    email: "fmccheynes@exblog.jp",
    country: "China",
    shipping: "61 Cody Center",
    source: "BigCommerce",
    order_type: "online",
  },
  {
    id: 30,
    shipfyId: "#5ffc2e",
    data: "02-12-2023",
    status: "pending",
    name: "Joellyn Abramsky",
    email: "jabramskyt@squarespace.com",
    country: "China",
    shipping: "80989 Heath Park",
    source: "WooCommerce",
    order_type: "online",
  },
  {
    id: 31,
    shipfyId: "#4999be",
    data: "15-10-2023",
    status: "failed",
    name: "Avigdor Wellstead",
    email: "awellsteadu@bbb.org",
    country: "Indonesia",
    shipping: "5 Hoepker Alley",
    source: "Shopware",
    order_type: "mobile app",
  },
  {
    id: 32,
    shipfyId: "#7cfd05",
    data: "10-09-2023",
    status: "pending",
    name: "Carlynne Aartsen",
    email: "caartsenv@va.gov",
    country: "Philippines",
    shipping: "598 Manley Hill",
    source: "Shopify",
    order_type: "in-store",
  },
  {
    id: 33,
    shipfyId: "#eafbeb",
    data: "16-01-2024",
    status: "pending",
    name: "August Measom",
    email: "ameasomw@wikipedia.org",
    country: "Philippines",
    shipping: "03916 Sullivan Park",
    source: "BigCommerce",
    order_type: "mobile app",
  },
  {
    id: 34,
    shipfyId: "#c8fcc7",
    data: "19-05-2023",
    status: "processing",
    name: "Jamie Scade",
    email: "jscadex@imgur.com",
    country: "China",
    shipping: "10 Monica Hill",
    source: "WooCommerce",
    order_type: "mobile app",
  },
  {
    id: 35,
    shipfyId: "#0db7d5",
    data: "27-04-2023",
    status: "pending",
    name: "Teodoro Cardenosa",
    email: "tcardenosay@wordpress.org",
    country: "Mexico",
    shipping: "94 Welch Alley",
    source: "Shopify",
    order_type: "phone",
  },
  {
    id: 36,
    shipfyId: "#40d359",
    data: "16-06-2023",
    status: "processing",
    name: "Mason Jaulmes",
    email: "mjaulmesz@clickbank.net",
    country: "France",
    shipping: "839 Melody Point",
    source: "BigCommerce",
    order_type: "phone",
  },
  {
    id: 37,
    shipfyId: "#fcc46e",
    data: "31-05-2023",
    status: "pending",
    name: "Hodge Garrard",
    email: "hgarrard10@guardian.co.uk",
    country: "Tanzania",
    shipping: "126 Oriole Circle",
    source: "Shopify",
    order_type: "in-store",
  },
  {
    id: 38,
    shipfyId: "#22ce42",
    data: "28-04-2023",
    status: "failed",
    name: "Georgena Foran",
    email: "gforan11@msu.edu",
    country: "Gabon",
    shipping: "919 Melby Plaza",
    source: "WooCommerce",
    order_type: "phone",
  },
  {
    id: 39,
    shipfyId: "#424ddf",
    data: "30-09-2023",
    status: "failed",
    name: "Dillie Stollberg",
    email: "dstollberg12@skyrock.com",
    country: "China",
    shipping: "2578 Raven Drive",
    source: "WooCommerce",
    order_type: "mobile app",
  },
  {
    id: 40,
    shipfyId: "#06afba",
    data: "08-12-2023",
    status: "processing",
    name: "Inna Iamittii",
    email: "iiamittii13@surveymonkey.com",
    country: "Thailand",
    shipping: "45157 Heffernan Pass",
    source: "Shopware",
    order_type: "in-store",
  },
  {
    id: 41,
    shipfyId: "#71b4a9",
    data: "30-07-2023",
    status: "failed",
    name: "Livia Margiotta",
    email: "lmargiotta14@flavors.me",
    country: "Pakistan",
    shipping: "7073 Dryden Terrace",
    source: "BigCommerce",
    order_type: "mobile app",
  },
  {
    id: 42,
    shipfyId: "#1610e7",
    data: "02-01-2024",
    status: "pending",
    name: "Miranda Ingolotti",
    email: "mingolotti15@youku.com",
    country: "China",
    shipping: "19 Springs Hill",
    source: "Shopify",
    order_type: "mobile app",
  },
  {
    id: 43,
    shipfyId: "#c4959d",
    data: "10-12-2023",
    status: "success",
    name: "Cris Ferguson",
    email: "cferguson16@baidu.com",
    country: "Poland",
    shipping: "0846 Packers Drive",
    source: "BigCommerce",
    order_type: "online",
  },
  {
    id: 44,
    shipfyId: "#11dfee",
    data: "01-01-2024",
    status: "failed",
    name: "Gannon Thaw",
    email: "gthaw17@livejournal.com",
    country: "Mexico",
    shipping: "359 Upham Circle",
    source: "BigCommerce",
    order_type: "phone",
  },
  {
    id: 45,
    shipfyId: "#e7f2c7",
    data: "10-11-2023",
    status: "failed",
    name: "Jarrod Orridge",
    email: "jorridge18@buzzfeed.com",
    country: "Yemen",
    shipping: "5 Dwight Center",
    source: "Magento",
    order_type: "online",
  },
  {
    id: 46,
    shipfyId: "#6714dd",
    data: "19-09-2023",
    status: "success",
    name: "Georgie Blasik",
    email: "gblasik19@ucsd.edu",
    country: "Czech Republic",
    shipping: "5682 Fairview Center",
    source: "Magento",
    order_type: "mobile app",
  },
  {
    id: 47,
    shipfyId: "#36107f",
    data: "17-07-2023",
    status: "pending",
    name: "Lawton Yapp",
    email: "lyapp1a@exblog.jp",
    country: "Vietnam",
    shipping: "1 Barnett Road",
    source: "WooCommerce",
    order_type: "phone",
  },
  {
    id: 48,
    shipfyId: "#d788bc",
    data: "15-10-2023",
    status: "success",
    name: "Carol Wevell",
    email: "cwevell1b@miitbeian.gov.cn",
    country: "China",
    shipping: "4 Westerfield Street",
    source: "Shopify",
    order_type: "online",
  },
  {
    id: 49,
    shipfyId: "#bbab21",
    data: "30-11-2023",
    status: "processing",
    name: "Smitty Rowson",
    email: "srowson1c@sphinn.com",
    country: "Indonesia",
    shipping: "0626 Charing Cross Park",
    source: "Shopify",
    order_type: "mobile app",
  },
  {
    id: 50,
    shipfyId: "#1f41d4",
    data: "10-01-2024",
    status: "pending",
    name: "Hillier Fireman",
    email: "hfireman1d@senate.gov",
    country: "Syria",
    shipping: "260 Jay Park",
    source: "Magento",
    order_type: "phone",
  },
  {
    id: 51,
    shipfyId: "#ed8f4f",
    data: "13-11-2023",
    status: "pending",
    name: "Dicky Breward",
    email: "dbreward1e@google.co.jp",
    country: "China",
    shipping: "13292 Annamark Terrace",
    source: "BigCommerce",
    order_type: "online",
  },
  {
    id: 52,
    shipfyId: "#0b230e",
    data: "13-10-2023",
    status: "failed",
    name: "Natalina Sutton",
    email: "nsutton1f@salon.com",
    country: "China",
    shipping: "799 Charing Cross Lane",
    source: "BigCommerce",
    order_type: "phone",
  },
  {
    id: 53,
    shipfyId: "#c758de",
    data: "23-05-2023",
    status: "success",
    name: "Garik Powney",
    email: "gpowney1g@bloglovin.com",
    country: "China",
    shipping: "72 Warner Street",
    source: "WooCommerce",
    order_type: "online",
  },
  {
    id: 54,
    shipfyId: "#12fafd",
    data: "02-04-2023",
    status: "processing",
    name: "Rochella Exeter",
    email: "rexeter1h@springer.com",
    country: "Indonesia",
    shipping: "7 Cottonwood Center",
    source: "Shopify",
    order_type: "mobile app",
  },
  {
    id: 55,
    shipfyId: "#7c95cd",
    data: "28-12-2023",
    status: "failed",
    name: "Cynthea Acklands",
    email: "cacklands1i@godaddy.com",
    country: "Greece",
    shipping: "45 Canary Place",
    source: "BigCommerce",
    order_type: "phone",
  },
  {
    id: 56,
    shipfyId: "#02d3e8",
    data: "02-08-2023",
    status: "success",
    name: "Yorke Nursey",
    email: "ynursey1j@comsenz.com",
    country: "China",
    shipping: "852 Drewry Center",
    source: "Magento",
    order_type: "phone",
  },
  {
    id: 57,
    shipfyId: "#2d1faf",
    data: "19-03-2023",
    status: "failed",
    name: "Norman McQuorkel",
    email: "nmcquorkel1k@wikipedia.org",
    country: "Nigeria",
    shipping: "10076 Glendale Lane",
    source: "Shopware",
    order_type: "phone",
  },
  {
    id: 58,
    shipfyId: "#318038",
    data: "13-04-2023",
    status: "pending",
    name: "Inger Lickorish",
    email: "ilickorish1l@ca.gov",
    country: "China",
    shipping: "27 Dovetail Street",
    source: "WooCommerce",
    order_type: "mobile app",
  },
  {
    id: 59,
    shipfyId: "#c53069",
    data: "22-04-2023",
    status: "failed",
    name: "Donal Como",
    email: "dcomo1m@flavors.me",
    country: "Ethiopia",
    shipping: "7573 Thackeray Alley",
    source: "Shopify",
    order_type: "online",
  },
  {
    id: 60,
    shipfyId: "#c818af",
    data: "31-07-2023",
    status: "failed",
    name: "Izaak Nudde",
    email: "inudde1n@zdnet.com",
    country: "Slovenia",
    shipping: "16 Merchant Park",
    source: "Magento",
    order_type: "phone",
  },
  {
    id: 61,
    shipfyId: "#f0cb3a",
    data: "26-04-2023",
    status: "success",
    name: "Cyndie Ruppele",
    email: "cruppele1o@mapquest.com",
    country: "Philippines",
    shipping: "27 Farmco Court",
    source: "Shopware",
    order_type: "in-store",
  },
  {
    id: 62,
    shipfyId: "#757557",
    data: "30-03-2023",
    status: "processing",
    name: "Lira Buffham",
    email: "lbuffham1p@theatlantic.com",
    country: "China",
    shipping: "90 Walton Alley",
    source: "BigCommerce",
    order_type: "in-store",
  },
  {
    id: 63,
    shipfyId: "#5fe3b3",
    data: "02-10-2023",
    status: "pending",
    name: "Lacee Brockbank",
    email: "lbrockbank1q@soup.io",
    country: "Thailand",
    shipping: "07 Straubel Parkway",
    source: "WooCommerce",
    order_type: "phone",
  },
  {
    id: 64,
    shipfyId: "#5e61c4",
    data: "14-06-2023",
    status: "processing",
    name: "Derrek De Bruin",
    email: "dde1r@g.co",
    country: "Albania",
    shipping: "2 Merchant Place",
    source: "BigCommerce",
    order_type: "in-store",
  },
  {
    id: 65,
    shipfyId: "#d889e9",
    data: "22-03-2023",
    status: "success",
    name: "Egbert Roth",
    email: "eroth1s@twitpic.com",
    country: "Macedonia",
    shipping: "3 Anthes Circle",
    source: "Magento",
    order_type: "online",
  },
  {
    id: 66,
    shipfyId: "#2c00fd",
    data: "03-11-2023",
    status: "failed",
    name: "Eldredge Yepiskov",
    email: "eyepiskov1t@engadget.com",
    country: "China",
    shipping: "548 Sugar Plaza",
    source: "Shopify",
    order_type: "in-store",
  },
  {
    id: 67,
    shipfyId: "#512467",
    data: "13-01-2024",
    status: "pending",
    name: "Krysta Tweedell",
    email: "ktweedell1u@geocities.com",
    country: "Philippines",
    shipping: "586 Coolidge Parkway",
    source: "WooCommerce",
    order_type: "phone",
  },
  {
    id: 68,
    shipfyId: "#b0e3be",
    data: "01-08-2023",
    status: "pending",
    name: "Kala Auden",
    email: "kauden1v@omniture.com",
    country: "Philippines",
    shipping: "75 Warbler Terrace",
    source: "Shopify",
    order_type: "mobile app",
  },
  {
    id: 69,
    shipfyId: "#62e022",
    data: "21-07-2023",
    status: "success",
    name: "Bordy MacConnulty",
    email: "bmacconnulty1w@answers.com",
    country: "Philippines",
    shipping: "7790 Brentwood Road",
    source: "BigCommerce",
    order_type: "in-store",
  },
  {
    id: 70,
    shipfyId: "#535130",
    data: "08-07-2023",
    status: "processing",
    name: "Rock Savins",
    email: "rsavins1x@360.cn",
    country: "China",
    shipping: "41191 Westerfield Road",
    source: "Shopware",
    order_type: "mobile app",
  },
  {
    id: 71,
    shipfyId: "#9f9057",
    data: "16-08-2023",
    status: "success",
    name: "Allan Drei",
    email: "adrei1y@hatena.ne.jp",
    country: "Vietnam",
    shipping: "50 Melrose Drive",
    source: "Shopify",
    order_type: "in-store",
  },
  {
    id: 72,
    shipfyId: "#6b82f7",
    data: "06-01-2024",
    status: "processing",
    name: "Emmett Saladino",
    email: "esaladino1z@cmu.edu",
    country: "China",
    shipping: "7631 Sunfield Terrace",
    source: "BigCommerce",
    order_type: "online",
  },
  {
    id: 73,
    shipfyId: "#cf4e11",
    data: "19-10-2023",
    status: "failed",
    name: "Demetra Iskov",
    email: "diskov20@unc.edu",
    country: "Albania",
    shipping: "81 Leroy Pass",
    source: "Shopify",
    order_type: "mobile app",
  },
  {
    id: 74,
    shipfyId: "#009a4d",
    data: "11-08-2023",
    status: "success",
    name: "Reena Bastock",
    email: "rbastock21@bigcartel.com",
    country: "Botswana",
    shipping: "0024 Farragut Plaza",
    source: "WooCommerce",
    order_type: "online",
  },
  {
    id: 75,
    shipfyId: "#2b7290",
    data: "10-09-2023",
    status: "success",
    name: "Carson Ewing",
    email: "cewing22@github.com",
    country: "United States",
    shipping: "9 Beilfuss Crossing",
    source: "WooCommerce",
    order_type: "phone",
  },
  {
    id: 76,
    shipfyId: "#a96c42",
    data: "14-04-2023",
    status: "success",
    name: "Barbee Chowne",
    email: "bchowne23@booking.com",
    country: "Libya",
    shipping: "067 Anderson Plaza",
    source: "BigCommerce",
    order_type: "phone",
  },
  {
    id: 77,
    shipfyId: "#147870",
    data: "28-10-2023",
    status: "processing",
    name: "Whitaker Ferrea",
    email: "wferrea24@paginegialle.it",
    country: "South Africa",
    shipping: "3032 Clove Park",
    source: "Shopware",
    order_type: "mobile app",
  },
  {
    id: 78,
    shipfyId: "#5dac37",
    data: "21-02-2023",
    status: "processing",
    name: "Donella Snoddy",
    email: "dsnoddy25@wix.com",
    country: "Russia",
    shipping: "93 High Crossing Point",
    source: "BigCommerce",
    order_type: "phone",
  },
  {
    id: 79,
    shipfyId: "#0b4db4",
    data: "05-08-2023",
    status: "success",
    name: "Stanislas Byford",
    email: "sbyford26@wordpress.com",
    country: "Canada",
    shipping: "2732 Carioca Junction",
    source: "Shopware",
    order_type: "mobile app",
  },
  {
    id: 80,
    shipfyId: "#78c75e",
    data: "20-10-2023",
    status: "success",
    name: "Rockie Conen",
    email: "rconen27@4shared.com",
    country: "Portugal",
    shipping: "23 Paget Place",
    source: "BigCommerce",
    order_type: "mobile app",
  },
  {
    id: 81,
    shipfyId: "#1a48b6",
    data: "26-12-2023",
    status: "pending",
    name: "Jackelyn Bilborough",
    email: "jbilborough28@vistaprint.com",
    country: "Kazakhstan",
    shipping: "2 Dorton Parkway",
    source: "BigCommerce",
    order_type: "mobile app",
  },
  {
    id: 82,
    shipfyId: "#b21e4a",
    data: "27-06-2023",
    status: "success",
    name: "Arnaldo Madine",
    email: "amadine29@utexas.edu",
    country: "Brazil",
    shipping: "14 Maywood Parkway",
    source: "BigCommerce",
    order_type: "online",
  },
  {
    id: 83,
    shipfyId: "#6317ac",
    data: "31-10-2023",
    status: "failed",
    name: "Cordy Oxtoby",
    email: "coxtoby2a@cornell.edu",
    country: "Poland",
    shipping: "94 Hoard Place",
    source: "Shopify",
    order_type: "in-store",
  },
  {
    id: 84,
    shipfyId: "#c94d92",
    data: "24-11-2023",
    status: "failed",
    name: "Emmi Gerbl",
    email: "egerbl2b@youtube.com",
    country: "Portugal",
    shipping: "966 Warrior Point",
    source: "WooCommerce",
    order_type: "online",
  },
  {
    id: 85,
    shipfyId: "#4b749a",
    data: "07-07-2023",
    status: "processing",
    name: "Rosanna Trenbey",
    email: "rtrenbey2c@independent.co.uk",
    country: "Ghana",
    shipping: "8 Glendale Way",
    source: "BigCommerce",
    order_type: "in-store",
  },
  {
    id: 86,
    shipfyId: "#2bd8e5",
    data: "14-10-2023",
    status: "failed",
    name: "Gussie Speeks",
    email: "gspeeks2d@irs.gov",
    country: "United States",
    shipping: "024 Little Fleur Drive",
    source: "Shopware",
    order_type: "phone",
  },
  {
    id: 87,
    shipfyId: "#f88313",
    data: "24-02-2023",
    status: "failed",
    name: "Katerine Ogden",
    email: "kogden2e@shareasale.com",
    country: "Uzbekistan",
    shipping: "3839 Atwood Hill",
    source: "Magento",
    order_type: "phone",
  },
  {
    id: 88,
    shipfyId: "#ca1b89",
    data: "06-08-2023",
    status: "pending",
    name: "Cinda Messer",
    email: "cmesser2f@eventbrite.com",
    country: "Ukraine",
    shipping: "746 Carpenter Point",
    source: "BigCommerce",
    order_type: "online",
  },
  {
    id: 89,
    shipfyId: "#ef6c18",
    data: "31-03-2023",
    status: "pending",
    name: "Fulton McCarty",
    email: "fmccarty2g@ucoz.com",
    country: "United States",
    shipping: "817 Annamark Court",
    source: "Magento",
    order_type: "mobile app",
  },
  {
    id: 90,
    shipfyId: "#5432f4",
    data: "27-05-2023",
    status: "pending",
    name: "Ruthann Harness",
    email: "rharness2h@unicef.org",
    country: "United States",
    shipping: "6009 Walton Hill",
    source: "Shopify",
    order_type: "in-store",
  },
  {
    id: 91,
    shipfyId: "#de881d",
    data: "23-01-2024",
    status: "failed",
    name: "Frasquito Pellew",
    email: "fpellew2i@wisc.edu",
    country: "China",
    shipping: "23 Pankratz Circle",
    source: "Shopify",
    order_type: "phone",
  },
  {
    id: 92,
    shipfyId: "#b9143a",
    data: "03-01-2024",
    status: "success",
    name: "Leelah Usherwood",
    email: "lusherwood2j@cocolog-nifty.com",
    country: "China",
    shipping: "38179 Cottonwood Park",
    source: "Shopify",
    order_type: "phone",
  },
  {
    id: 93,
    shipfyId: "#dabe7a",
    data: "02-11-2023",
    status: "failed",
    name: "Nataniel Cusick",
    email: "ncusick2k@mozilla.org",
    country: "Canada",
    shipping: "33100 Elgar Lane",
    source: "Shopify",
    order_type: "phone",
  },
  {
    id: 94,
    shipfyId: "#1bf2f6",
    data: "27-12-2023",
    status: "failed",
    name: "Enid Avrahamov",
    email: "eavrahamov2l@answers.com",
    country: "France",
    shipping: "17 Gale Alley",
    source: "Shopify",
    order_type: "mobile app",
  },
  {
    id: 95,
    shipfyId: "#21c94f",
    data: "15-08-2023",
    status: "success",
    name: "Tedda Gerler",
    email: "tgerler2m@weibo.com",
    country: "United Kingdom",
    shipping: "3918 Burrows Road",
    source: "WooCommerce",
    order_type: "phone",
  },
  {
    id: 96,
    shipfyId: "#8645a4",
    data: "04-07-2023",
    status: "success",
    name: "Angelia Evason",
    email: "aevason2n@google.com.au",
    country: "Russia",
    shipping: "0 Moulton Plaza",
    source: "Shopware",
    order_type: "mobile app",
  },
  {
    id: 97,
    shipfyId: "#0258ee",
    data: "29-12-2023",
    status: "success",
    name: "Randa Sunderland",
    email: "rsunderland2o@devhub.com",
    country: "Nigeria",
    shipping: "7 Schiller Way",
    source: "Shopware",
    order_type: "phone",
  },
  {
    id: 98,
    shipfyId: "#45a7fd",
    data: "10-10-2023",
    status: "failed",
    name: "Godwin Klimov",
    email: "gklimov2p@indiatimes.com",
    country: "Ukraine",
    shipping: "811 Bowman Terrace",
    source: "Shopify",
    order_type: "in-store",
  },
  {
    id: 99,
    shipfyId: "#661b88",
    data: "04-07-2023",
    status: "failed",
    name: "Ethyl Breawood",
    email: "ebreawood2q@google.pl",
    country: "Cuba",
    shipping: "42 Division Court",
    source: "WooCommerce",
    order_type: "in-store",
  },
  {
    id: 100,
    shipfyId: "#cffe97",
    data: "25-01-2024",
    status: "success",
    name: "Sheelagh Vlasov",
    email: "svlasov2r@amazon.co.uk",
    country: "Colombia",
    shipping: "97147 Mifflin Center",
    source: "Shopware",
    order_type: "mobile app",
  },
];
